stages:
  eda_clean:
    cmd: python src/proyecto_mlops/data/clean.py --cfg configs/eda.yaml
    deps:
      - src/proyecto_mlops/data/clean.py
      - configs/eda.yaml
      - data/raw
    outs:
      - data/processed
  features:
    cmd: python src/proyecto_mlops/features/build_features.py --cfg configs/features.yaml
    deps:
      - src/proyecto_mlops/features/build_features.py
      - configs/features.yaml
      - data/processed
    outs:
      - data/interim
  train:
    cmd: python src/proyecto_mlops/modelling/train.py --cfg configs/train.yaml
    deps:
      - src/proyecto_mlops/modelling/train.py
      - configs/train.yaml
      - data/interim
    outs:
      - artifacts/model.pkl
