stages:
  data_cleaning:
    cmd: python src/data_cleaning/clean.py --cfg configs/eda.yaml
    deps:
      - src/data_cleaning/clean.py
      - configs/eda.yaml
      - data/raw
    outs:
      - data/processed

  features:
    cmd: python src/features.py
    deps:
      - src/features.py
      - configs/features.yaml
      - data/processed/clean.csv
    outs:
      - data/interim

  train:
    cmd: python src/modelling/train.py --cfg configs/train.yaml
    deps:
      - src/modelling/train.py
      - configs/train.yaml
      - data/interim
    outs:
      - models/best_model.pkl
    metrics:
      - reports/metrics.json:
          cache: false

  graphic_analysis:
    cmd: python src/visualization/plots.py
    deps:
      - src/visualization/plots.py
      - models/best_model.pkl
    outs:
      - reports/figures