stages:
  # eda_clean:
  #   cmd: python src/proyecto_mlops/data/clean.py --cfg configs/eda.yaml
  #   deps:
  #     - src/proyecto_mlops/data/clean.py
  #     - configs/eda.yaml
  #     - data/raw
  #   outs:
  #     - data/processed

  features:
    cmd: PYTHONPATH=src python src/proyecto_mlops/features.py
    deps:
      - src/proyecto_mlops/features.py
      - configs/features.yaml
      - src/proyecto_mlops/data/processed/clean.csv
    outs:
      - data/interim

  train:
    cmd: PYTHONPATH=src python src/proyecto_mlops/modelling/train.py --cfg configs/train.yaml
    deps:
      - src/proyecto_mlops/modelling/train.py
      - configs/train.yaml
      - data/interim
    outs:
      - artifacts/model.pkl
    metrics:
      - reports/metrics.json:
          cache: false

  evaluate:
    cmd: python src/proyecto_mlops/visualization/plots.py
    deps:
      - src/proyecto_mlops/visualization/plots.py
      - artifacts/model.pkl
    outs:
      - reports/figures
