target: Load_Type
numeric_features:
  - Usage_kWh
  - Lagging_Current_Reactive.Power_kVarh
  - Leading_Current_Reactive_Power_kVarh
  - CO2(tCO2)
  - Lagging_Current_Power_Factor
  - Leading_Current_Power_Factor
  - NSM
  - mixed_type_col
test_size: 0.12
val_size: 0.2
stratify: true
outer_split_random_state: 0
inner_split_random_state: 5
model_random_state: 42
cv_n_splits: 3
cv_n_repeats: 1
search_cv_splits: 3
